<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/12/12
 * Time: 14:22
 */

namespace App;
use App\Events\CrudLogEvent;
use App\Http\Middleware\LogCurd;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Event;

class Blog extends Model{
    protected $table = 'blog';
    protected $fillable = ['title', 'author','tag','content','author_pic'];
    public function posts(){

        return $this->hasMany('App\Post','blog_id','id');
    }

    public function delete()
    {

    }

    public function update(array $attributes = [], array $options = [])
    {
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }

    public function create(){

    }

    public function search(){

    }
}